-- Online orders are sales too: same items, same stock. A counter sale is STORE / COMPLETED;
-- an online order is ONLINE and goes NEW -> CONFIRMED -> SHIPPED -> DELIVERED (or CANCELLED / RETURNED).
alter table sales add column channel varchar(10) default 'STORE' not null;
alter table sales add column status varchar(20) default 'COMPLETED' not null;
-- The number the customer sees, e.g. TS-7K3F9Q (online orders only)
alter table sales add column order_number varchar(20);
-- Where to deliver, copied onto the order (it must not change if the customer moves later)
alter table sales add column delivery_name varchar(100);
alter table sales add column delivery_phone varchar(20);
alter table sales add column delivery_city varchar(80);
alter table sales add column delivery_address varchar(255);
alter table sales add column delivery_note varchar(500);
alter table sales add column delivery_fee numeric(10,2) default 0 not null;

alter table sales add constraint uk_sales_order_number unique (order_number);
create index idx_sales_status on sales (status);
create index idx_sales_delivery_phone on sales (delivery_phone);

-- Every status an order went through, with who changed it and when
create table order_status_changes (
    id bigint generated by default as identity,
    sale_id bigint not null,
    status varchar(20) not null,
    note varchar(255),
    changed_by varchar(50) not null,
    changed_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_order_status_changes_sale foreign key (sale_id) references sales
);

create index idx_order_status_changes_sale_id on order_status_changes (sale_id);
