-- Initial schema: exactly what Hibernate generated for the entities before Flyway was added,
-- so existing databases (baselined at version 1) and new ones end up identical.

create table customers (
    id bigint generated by default as identity,
    phone varchar(30),
    name varchar(100) not null,
    email varchar(150) unique,
    primary key (id)
);

create table products (
    price numeric(10,2) not null,
    quantity integer not null,
    id bigint generated by default as identity,
    name varchar(150) not null,
    primary key (id)
);

create table sales (
    customer_id bigint not null,
    id bigint generated by default as identity,
    sale_date timestamp(6) not null,
    primary key (id)
);

create table sale_items (
    quantity integer not null,
    unit_price numeric(10,2) not null,
    id bigint generated by default as identity,
    product_id bigint not null,
    sale_id bigint not null,
    primary key (id)
);

alter table if exists sale_items
    add constraint FK8g0sjiqs7tg055o06p6wawu39
    foreign key (product_id)
    references products;

alter table if exists sale_items
    add constraint FK7tcpbc5c5mpnm8fl2phl8ep7l
    foreign key (sale_id)
    references sales;

alter table if exists sales
    add constraint FKd94vrikapjd2ews1k4lb71sfg
    foreign key (customer_id)
    references customers;
