-- Accounts that can log in to the API. Passwords are stored as BCrypt hashes, never in clear.
create table app_users (
    id bigint generated by default as identity,
    username varchar(50) not null unique,
    password_hash varchar(100) not null,
    role varchar(20) not null,
    enabled boolean not null,
    primary key (id)
);
