-- Low-stock alerts: a product is low when its quantity is at or below min_quantity
alter table products add column min_quantity integer default 0 not null;

-- Every change to a product's stock, with who made it and when
create table stock_movements (
    id bigint generated by default as identity,
    product_id bigint not null,
    type varchar(20) not null,
    quantity_change integer not null,
    quantity_after integer not null,
    reason varchar(255),
    sale_item_id bigint,
    created_by varchar(50) not null,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_stock_movements_product foreign key (product_id) references products
);

create index idx_stock_movements_product_id on stock_movements (product_id);
