-- Product categories, one level (e.g. Phones, Audio, Chargers & cables).
-- A product has at most one category; products without one are "uncategorized".
create table categories (
    id bigint generated by default as identity,
    name varchar(50) not null,
    primary key (id),
    constraint uk_categories_name unique (name)
);

alter table products add column category_id bigint;
alter table products add constraint fk_products_category foreign key (category_id) references categories;
create index idx_products_category_id on products (category_id);
