-- Every change to a product's price, with who made it and when (like the stock history)
create table price_changes (
    id bigint generated by default as identity,
    product_id bigint not null,
    old_price numeric(10,2) not null,
    new_price numeric(10,2) not null,
    changed_by varchar(50) not null,
    changed_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_price_changes_product foreign key (product_id) references products
);

create index idx_price_changes_product_id on price_changes (product_id);

-- After a price drop: the struck-through price to show, and when the drop happened
-- (it is shown for 30 days; see PriceHistoryService)
alter table products add column previous_price numeric(10,2);
alter table products add column price_reduced_at timestamp(6) with time zone;
