-- Product pictures. The details are here; the image itself is in product_image_files,
-- so listing products never loads image bytes. The first picture (lowest sort_order) is the cover.
create table product_images (
    id bigint generated by default as identity,
    product_id bigint not null,
    sort_order integer not null,
    width integer not null,
    height integer not null,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint fk_product_images_product foreign key (product_id) references products
);

create index idx_product_images_product_id on product_images (product_id);

-- The picture as a JPEG, re-encoded by the server (see ProductPictureService)
create table product_image_files (
    image_id bigint not null,
    content bytea not null,
    primary key (image_id),
    constraint fk_product_image_files_image foreign key (image_id) references product_images
);

-- Optional text about the product, for the online shop
alter table products add column description varchar(2000);
